// <auto-generated />
using System;
using DCF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DCF.Data.Migrations
{
    [DbContext(typeof(DcfDbContext))]
    partial class DcfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DCF.Data.Entities.CorpsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Corps");
                });

            modelBuilder.Entity("DCF.Data.Entities.DraftPickEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Caption")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorpsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<int>("PickNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorpsId");

                    b.HasIndex("UserId", "LeagueId");

                    b.HasIndex("LeagueId", "CorpsId", "Caption")
                        .IsUnique();

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("DCF.Data.Entities.LeagueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommissionerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorpsPerCaption")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentPickNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DraftOrderJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DraftStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DraftStatus")
                        .HasColumnType("integer");

                    b.Property<string>("DraftableCaptions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommissionerUserId");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("SeasonId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("DCF.Data.Entities.LeagueMemberEntity", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LeagueId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LeagueMembers");
                });

            modelBuilder.Entity("DCF.Data.Entities.ScoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Caption")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorpsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Judge")
                        .HasColumnType("text");

                    b.Property<int>("PerformanceRank")
                        .HasColumnType("integer");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("double precision");

                    b.Property<int>("RepertoireRank")
                        .HasColumnType("integer");

                    b.Property<double>("RepertoireScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalRank")
                        .HasColumnType("integer");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.HasIndex("CorpsId", "ShowId", "Caption")
                        .IsUnique();

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("DCF.Data.Entities.SeasonCorpsEntity", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorpsId")
                        .HasColumnType("uuid");

                    b.HasKey("SeasonId", "CorpsId");

                    b.HasIndex("CorpsId");

                    b.ToTable("SeasonCorps");
                });

            modelBuilder.Entity("DCF.Data.Entities.SeasonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("DCF.Data.Entities.ShowCorpsEntity", b =>
                {
                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorpsId")
                        .HasColumnType("uuid");

                    b.HasKey("ShowId", "CorpsId");

                    b.HasIndex("CorpsId");

                    b.ToTable("ShowCorps");
                });

            modelBuilder.Entity("DCF.Data.Entities.ShowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScoresAnnouncedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("DCF.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Sub")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DCF.Data.Entities.DraftPickEntity", b =>
                {
                    b.HasOne("DCF.Data.Entities.CorpsEntity", "Corps")
                        .WithMany("DraftPicks")
                        .HasForeignKey("CorpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCF.Data.Entities.LeagueEntity", "League")
                        .WithMany("DraftPicks")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCF.Data.Entities.UserEntity", "User")
                        .WithMany("DraftPicks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corps");

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DCF.Data.Entities.LeagueEntity", b =>
                {
                    b.HasOne("DCF.Data.Entities.UserEntity", "Commissioner")
                        .WithMany("CommissionedLeagues")
                        .HasForeignKey("CommissionerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCF.Data.Entities.SeasonEntity", "Season")
                        .WithMany("Leagues")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commissioner");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DCF.Data.Entities.LeagueMemberEntity", b =>
                {
                    b.HasOne("DCF.Data.Entities.LeagueEntity", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCF.Data.Entities.UserEntity", "User")
                        .WithMany("LeagueMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DCF.Data.Entities.ScoreEntity", b =>
                {
                    b.HasOne("DCF.Data.Entities.CorpsEntity", "Corps")
                        .WithMany("Scores")
                        .HasForeignKey("CorpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCF.Data.Entities.ShowEntity", "Show")
                        .WithMany("Scores")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corps");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("DCF.Data.Entities.SeasonCorpsEntity", b =>
                {
                    b.HasOne("DCF.Data.Entities.CorpsEntity", "Corps")
                        .WithMany("SeasonCorps")
                        .HasForeignKey("CorpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCF.Data.Entities.SeasonEntity", "Season")
                        .WithMany("SeasonCorps")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corps");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DCF.Data.Entities.ShowCorpsEntity", b =>
                {
                    b.HasOne("DCF.Data.Entities.CorpsEntity", "Corps")
                        .WithMany("ShowCorps")
                        .HasForeignKey("CorpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DCF.Data.Entities.ShowEntity", "Show")
                        .WithMany("ShowCorps")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corps");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("DCF.Data.Entities.ShowEntity", b =>
                {
                    b.HasOne("DCF.Data.Entities.SeasonEntity", "Season")
                        .WithMany("Shows")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DCF.Data.Entities.CorpsEntity", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("Scores");

                    b.Navigation("SeasonCorps");

                    b.Navigation("ShowCorps");
                });

            modelBuilder.Entity("DCF.Data.Entities.LeagueEntity", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("DCF.Data.Entities.SeasonEntity", b =>
                {
                    b.Navigation("Leagues");

                    b.Navigation("SeasonCorps");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("DCF.Data.Entities.ShowEntity", b =>
                {
                    b.Navigation("Scores");

                    b.Navigation("ShowCorps");
                });

            modelBuilder.Entity("DCF.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("CommissionedLeagues");

                    b.Navigation("DraftPicks");

                    b.Navigation("LeagueMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
